---
- name: Reset Password Superset
  hosts: superset
  become: yes
  gather_facts: no

  tasks:
    - name: Define Superset environment variables
      set_fact:
        superset_env_vars:
          FLASK_APP: superset
          SUPERSET_CONFIG_PATH: "{{ superset_config_path }}"
          SUPERSET_SECRET_KEY: "{{ superset_secret_key }}"

    - name: Check if new Superset user already exists
      ansible.builtin.shell: |
        . {{ superset_venv_dir }}/bin/activate
        superset fab list-users | grep '{{ superset_username }}'
      environment: "{{ superset_env_vars }}"
      become_user: "{{ superset_user }}"
      register: check_user_exists
      failed_when: check_user_exists.rc not in [0, 1]
      changed_when: false

    - name: Reset Password for Superset user "{{ superset_username }}"
      ansible.builtin.shell: |
        . {{ superset_venv_dir }}/bin/activate
        superset fab reset-password --username "{{ superset_username }}" --password "{{ superset_password }}"
      environment: "{{ superset_env_vars }}"
      become_user: "{{ superset_user }}"
      args:
        stdin: |
          "{{ superset_password }}"
          "{{ superset_password }}"
      when: check_user_exists.rc == 0
      changed_when: true
